volumes:
    postgres_data:
        driver: local
    minio_data:
        driver: local

services:
    postgres:
        # you can connect with e.g.
        # psql -h localhost -p 5555 -U postgres -d db
        image: postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5556:5432"
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"

    minio:
        image: minio/minio:latest
        restart: always
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin123
        command: server /data --console-address ":9001"
