import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";
import Script from "next/script";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ThemeProvider } from "next-themes";

import { Providers } from "@/app/providers";
import Header from "@/components/header";
import { NotificationProvider } from "@/components/ui/notification-provider";
import { Provider as TooltipProvider } from "@/components/ui/tooltip";
import { env } from "@/env";
import { cn } from "@/lib/utils/cn";

import type { Metadata } from "next";
import "./globals.css";

const inter = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

const geistMono = localFont({
    src: "./fonts/GeistMono[wght].woff2",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();

    // Providing all messages to the client
    // side is the easiest way to get started
    const messages = await getMessages();
    return (
        <html
            lang={locale}
            suppressHydrationWarning
            className={cn(inter.variable, geistMono.variable, "antialiased")}
        >
            {env.NEXT_PUBLIC_REACT_SCAN_DEVTOOLS === "true" &&
                env.NODE_ENV === "development" && (
                    <Script
                        crossOrigin="anonymous"
                        src="//unpkg.com/react-scan/dist/auto.global.js"
                    />
                )}
            <body className="bg-bg-white-0 text-text-strong-950">
                <NextIntlClientProvider messages={messages}>
                    <ThemeProvider attribute="class">
                        <TooltipProvider>
                            <Providers>
                                <div className="flex min-h-screen flex-col">
                                    <Header />
                                    <main className="flex flex-1 flex-col">
                                        {children}
                                    </main>
                                </div>
                            </Providers>
                        </TooltipProvider>
                    </ThemeProvider>
                    <NotificationProvider />
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
